#!/bin/bash

mvn install:install-file -Dfile=target/com.kainos.training.jersey.client-0.0.1-SNAPSHOT.jar -DgroupId=jersey-client -DartifactId=com.kainos.training.jersey.client -Dversion=0.0.1-SNAPSHOT -Dpackaging=jar